server:
  port: 8888

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vvv09/microservices-config-server
          clone-on-start: true
          default-label: master
