version: "3.9"
services:
  postgres-app-db:
    container_name: app_database
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    networks:
      - ${GLOBAL_NETWORK:-services}
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:5.1
    env_file:
      - ./.env
    ports:
      - "5050:80"
    networks:
      - ${GLOBAL_NETWORK:-services}