server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: oreder-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/application-database
    username: user
    password: pass
    currentSchema: order_service
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always